export const peopleJson = [
  {
    Timestamp: '2020/05/13 1:56:37 PM MDT',
    Name: 'Mitesh Patel',
    'Job Title': 'Senior Research Scientist',
    'Job Function': 'Research & Development',
    Location: 'San Francisco Bay Area',
    'Location Options': 'Open to Remote',
    Description:
      'Over 10 years of research experience in modelling user behavior using low level sensors, sensor fusion, indoor localization, data mining and applying machine learning algorithms including probabilistic graphical models, classification, regression to a given problem',
    LinkedIn: 'http://www.linkedin.com/in/patelmiteshn',
    GitHub: 'http://www.github.com/patelmiteshn',
    'Twitter?': '',
    Instagram: '',
    'Google Scholar': 'https://tinyurl.com/t5hh5lg',
    Resume: 'https://drive.google.com/open?id=15DxWGnMmYhVDqplt_zOz4Abs4nJiWktj',
    'Other Website': '',
    'Pretty Name for Other Website': '',
    Photo: 'https://drive.google.com/u/0/open?usp=forms_web&id=1iaccbsldV0S42KVJ51Ji0L31R-aj0eYM'
  },
  {
    Timestamp: '2020/05/13 2:22:55 PM MDT',
    Name: 'David Ayman Shamma',
    'Job Title': 'Senior Research Scientist',
    'Job Function': 'Research, Prototyping, Engineering',
    Location: 'San Francisco',
    'Location Options': 'Open to Remote',
    Description:
      'At FXPAL, my research focused on the intersection of AI and human-computer interaction; I designed, developed, prototyped, tested, and patented many future-of-work systems including: AI for smart consumer cameras, enterprise devices, and IoT, gaze and presence in 360° video conferencing, VR environments for remote meetings.  This included architecting backend systems, as well as, working with designers for 3D device prototypes.  My prior 10 years experience was at Yahoo Labs where I was the Director of Research at Flickr and working on social computing.',
    LinkedIn: 'https://www.linkedin.com/in/aymans/',
    GitHub: 'https://github.com/ayman/',
    'Twitter?': 'https://twitter.com/ayman/',
    Instagram: 'https://www.instagram.com/aymans/',
    'Google Scholar': 'https://scholar.google.com/citations?user=ge8g4uoAAAAJ&hl=en',
    Resume: 'http://shamur.ai/cv.pdf',
    'Other Website': 'https://shamur.ai/',
    'Pretty Name for Other Website': 'Website',
    Photo: 'https://drive.google.com/u/0/open?usp=forms_web&id=1UFbNb6CH1A4G3Nzld14P4OEGXKE1hOiV'
  },
  {
    Timestamp: '2020/05/13 4:07:39 PM MDT',
    Name: 'Kandha Sankarapandian',
    'Job Title': 'Senior Development Manager',
    'Job Function': 'Engineering, Business Innovation',
    Location: 'San Francisco Bay Area',
    'Location Options': 'Open to Remote',
    Description:
      'Hands-on Senior Development Manager with 15 years of technical leadership, team mentorship and strong coding, prototyping skills. Experienced in leading and mentoring global product development teams of various sizes, with multiple successful product & business launches under the belt. Evaluated and helped adopt cutting edge technologies such as Machine Learning, Serverless Computing, DevOps, IoT, Blockchain etc. for agile prototyping and eventual productization. Expert at Lean Innovation with multiple granted US patents. Usable Security specialist.',
    LinkedIn: 'https://www.linkedin.com/in/kandhas/',
    GitHub: '',
    'Twitter?': '',
    Instagram: '',
    'Google Scholar': '',
    Resume: 'https://drive.google.com/open?id=1obSdnc5aSKym3usMNc74LNLfUg7L_Fhl',
    'Other Website': '',
    'Pretty Name for Other Website': '',
    Photo: 'https://drive.google.com/u/0/open?usp=forms_web&id=1v15ZHvKDnyIElS5Cm0gauzDoF6GLWjyJ'
  },
  {
    Timestamp: '2020/05/13 5:21:30 PM MDT',
    Name: 'Andreas Girgensohn',
    'Job Title': 'Distinguished Scientist',
    'Job Function': 'Research, Engineering',
    Location: 'San Francisco Bay Area',
    'Location Options': '',
    Description:
      'Accomplished researcher leveraging multimedia and HCI for creating rich, usable multimedia applications such as video surveillance, leading to many patents and publications.  Filled the roles of full-stack engineer and software architect for web-based, iOS, and Android projects.  Very familiar with frameworks and languages such as React, Node.js, Numpy, Flask, JAX-RS, JavaScript, Java, Swift, C++, C#, Docker, AWS.',
    LinkedIn: 'https://www.linkedin.com/in/andreas-girgensohn-764110/',
    GitHub: 'https://github.com/andreasg123',
    'Twitter?': '',
    Instagram: '',
    'Google Scholar': 'https://scholar.google.com/citations?user=Dz6O99EAAAAJ',
    Resume: 'https://www.webcollab.com/andreasg/resume.html',
    'Other Website':
      'http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Girgensohn%3B+Andreas&FIELD1=INNM&co1=AND&TERM2=&FIELD2=&d=PTXT',
    'Pretty Name for Other Website': 'Patents',
    Photo: 'https://drive.google.com/u/0/open?usp=forms_web&id=1uYWUnKCwiwjonptyNm7fWa6q0ZUVXfF0'
  },
  {
    Timestamp: '2020/05/13 6:03:49 PM MDT',
    Name: 'Yanxia Zhang',
    'Job Title': 'Research Scientist',
    'Job Function': 'Research, Engineering',
    Location: 'San Francisco Bay Area',
    'Location Options': '',
    Description: 'Machine learning, Computer Vision, Data Science',
    LinkedIn: '',
    GitHub: '',
    'Twitter?': '',
    Instagram: '',
    'Google Scholar': '',
    Resume: '',
    'Other Website': '',
    'Pretty Name for Other Website': '',
    Photo: ''
  }
];
