export const peopleMap = {
  'Andreas Girgensohn': 'andreas.jpg',
  'David Ayman Shamma': 'ayman.jpg',
  b: 'bee.png',
  c: 'carter.jpg',
  c2: 'chelhwon.jpg',
  c3: 'chidansh.jpg',
  d: 'daniel.jpg',
  f: 'filby.jpg',
  h: 'hao.jpg',
  'Kandha Sankarapandian': 'kandha.jpg',
  k: 'kimber.jpg',
  l: 'lyndon.jpg',
  m: 'mattlee.jpg',
  'Mitesh Patel': 'mitesh.jpg',
  q: 'qiong.jpg',
  t: 'tony.jpg',
  'Yanxia Zhang': 'yanxia.jpg',
  y: 'yanying.jpg'
};
