export const peopleMap = {
  'Andreas Girgensohn': { image: 'andreas.jpg', blurhash: 'UTHUIaIn0zxD00xaIooz.ToJ-VNF4nWBs:of' },
  'David Ayman Shamma': { image: 'ayman.jpg', pubSearch: 'David Shamma', blurhash: 'UhI5MRR4yEtQ~pM_%MtRR*jsr=xui^$*Rjs:' },
  b: 'bee.png',
  c: 'carter.jpg',
  c2: 'chelhwon.jpg',
  c3: 'chidansh.jpg',
  'Daniel Avrahami': { image: 'daniel.jpg', blurhash: 'UcKwd[x]~pxu-pV@WCj?9aWAM{Rk-okCRjWB' },
  f: 'filby.jpg',
  h: 'hao.jpg',
  'Kandha Sankarapandian': { image: 'kandha.jpg', blurhash: 'UKH-og~UGZI:MvIVITIoK+xt~VjsoZRlawni' },
  k: 'kimber.jpg',
  'Laurent Denoue': { image: 'laurent.jpg', blurhash: 'U9CO:#9]0$~BF|-7M{E%0~XS^3Rj9]xa$iNG' },
  l: 'lyndon.jpg',
  m: 'mattlee.jpg',
  'Mitesh Patel': { image: 'mitesh.jpg', blurhash: 'U9Gb-N0Kl.9X0w?cR6-.yrD%}s9FnLM_56t6' },
  q: 'qiong.jpg',
  'Anthony Dunnigan': { image: 'tony.jpg', pubSearch: 'Tony Dunnigan', blurhash: 'UsIr1*MxRkj?.TM{axay^,R*RjWC%Mt7WBWB' },
  'Yanxia Zhang': { image: 'yanxia.jpg', blurhash: 'UWIOtXSe?[xbM[t5ou%2%$tQRQofRiRjxuog' },
  y: 'yanying.jpg'
};
